name: Continuous Deployment(Backend)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to Docker Hub    
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: alexgoot/staff_backend:${{ github.sha }}

      - name: Debug database URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"

      - name: Deploy to the VM
        run: |
          echo "${{ secrets.SSH_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key Shrirang@4.213.167.255 << 'EOF'
           sudo docker network create staffingUp-network || true
           sudo docker stop backend || true
           sudo docker rm backend || true
           sudo docker stop postgres || true
           sudo docker rm postgres || true

           sudo docker run -d \
              -e POSTGRES_PASSWORD=randompassword \
              --name postgres \
              --network staffingUp-network \
              postgres

                   sudo docker run -d \
                      -p 3000:3000 \
                      -e DATABASE_URL='${{ secrets.DATABASE_URL }}' \
                      -e DEV_JWT_SECRET='${{ secrets.DEV_JWT_SECRET }}' \
                      -e USER_JWT_SECRET='${{ secrets.USER_JWT_SECRET }}' \
                      -e OPENAI_API_KEY='${{ secrets.OPENAI_API_KEY }}' \
                      -e NEXT_PUBLIC_API_URL='${{ secrets.API_URL }}' \
                      -e WS_URL='${{ secrets.WS_URL }}' \
                      --name backend \
                      --network staffingUp-network \
                      alexgoot/staff_backend:${{ github.sha }} << 'EOF'
             
